# AI Smart Product Search Engine

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\User\Downloads\ecommerce_products_killer.csv",sep=',')

In [3]:
df.head()

,product_id,product_name,brand,category,subcategory,price,currency,discount_percent,discounted_price,rating,reviews_count,popularity_score,stock_status,date_added,description
0,P100000,iPhone 13,Apple,Electronics,Smartphone,65372,INR,57,28109.96,3.7,3050,11285.0,Limited Stock,2025-10-17,Apple iPhone 13 is a premium smartphone design...
1,P100001,Zara Shirt,Zara,Fashion,Shirt,2616,INR,55,1177.20,4.1,4699,19265.9,Out of Stock,2026-03-22,Zara Zara Shirt is a premium shirt designed fo...
2,P100002,RayBan Sunglasses,RayBan,Accessories,Sunglasses,1305,INR,58,548.10,3.6,1700,6120.0,In Stock,2025-07-12,RayBan RayBan Sunglasses is a premium sunglass...
3,P100003,Puma Sneakers,Puma,Footwear,Sneakers,7471,INR,60,2988.40,3.5,860,3010.0,In Stock,2026-04-12,Puma Puma Sneakers is a premium sneakers desig...
4,P100004,Nike T-shirt,Nike,Fashion,T-shirt,1305,INR,37,822.15,3.9,138,538.2,Limited Stock,2025-10-30,Nike Nike T-shirt is a premium t-shirt designe...

In [23]:
print("The shape is:",df.shape,"\n")
print(df.isnull().sum())
print("\nData Types:\n")
print(df.dtypes)

The shape is: (2000, 15)

product_id          0
product_name        0
brand               0
category            0
subcategory         0
price               0
currency            0
discount_percent    0
discounted_price    0
rating              0
reviews_count       0
popularity_score    0
stock_status        0
date_added          0
description         0
dtype: int64

Data Types:

product_id           object
product_name         object
brand                object
category             object
subcategory          object
price                 int64
currency             object
discount_percent      int64
discounted_price    float64
rating              float64
reviews_count         int64
popularity_score    float64
stock_status         object
date_added           object
description          object
dtype: object

In [21]:
print("Total Product:",len(df))
print("\nCategories:")
print(df['category'].value_counts())
print("\nSubcategories:")
print(df['subcategory'].value_counts())
print("\nBrands:")
print(df['brand'].value_counts())

Total Product: 2000

Categories:
category
Accessories    540
Electronics    507
Footwear       490
Fashion        463
Name: count, dtype: int64

Subcategories:
subcategory
Sneakers          242
Smartphone        234
Backpack          146
Sunglasses        137
Running Shoes     132
Laptop            130
Travel Bag        129
Watch             128
Training Shoes    116
Jacket             84
Sweatshirt         82
Shirt              78
Jeans              77
Headphones         73
T-shirt            71
Hoodie             71
Earbuds            70
Name: count, dtype: int64

Brands:
brand
Puma                  206
Adidas                203
Nike                  191
Wildcraft             146
RayBan                137
American Tourister    129
Fossil                128
Reebok                116
Apple                  83
H&M                    82
Zara                   78
OnePlus                77
Levi's                 77
Samsung                74
Sony                   73
Boat                   70
Dell                   66
HP                     64
Name: count, dtype: int64

In [24]:
print("Price Statistics (INR):")
print(f"  Average Price  : ₹{df['price'].mean():,.0f}")
print(f"  Minimum Price  : ₹{df['price'].min():,.0f}")
print(f"  Maximum Price  : ₹{df['price'].max():,.0f}")

print("\nRating Statistics:")
print(f"  Average Rating : {df['rating'].mean():.1f} ⭐")
print(f"  Min Rating     : {df['rating'].min()} ⭐")
print(f"  Max Rating     : {df['rating'].max()} ⭐")

print("\nStock Status:")
print(df['stock_status'].value_counts())

Price Statistics (INR):
  Average Price  : ₹14,561
  Minimum Price  : ₹329
  Maximum Price  : ₹79,998

Rating Statistics:
  Average Rating : 4.1 ⭐
  Min Rating     : 3.2 ⭐
  Max Rating     : 5.0 ⭐

Stock Status:
stock_status
In Stock         683
Out of Stock     662
Limited Stock    655
Name: count, dtype: int64

In [26]:
import nltk
import re
import warnings
warnings.filterwarnings('ignore')

# Download required nltk data
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

print("✅ Libraries ready!")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

✅ Libraries ready!

In [27]:
# Combine all text columns into one search column
df['search_text'] = (
    df['product_name'] + ' ' +
    df['brand'] + ' ' +
    df['category'] + ' ' +
    df['subcategory'] + ' ' +
    df['description']
)

print("Combined text column created!")
print("\nSample search text:")
print(df['search_text'][0])

Combined text column created!

Sample search text:
iPhone 13 Apple Electronics Smartphone Apple iPhone 13 is a premium smartphone designed for performance and comfort.

In [28]:
def clean_text(text):
    # Convert to lowercase
    text = text.lower()
    
    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # Remove stopwords
    words = text.split()
    words = [w for w in words if w not in stop_words]
    
    return ' '.join(words)

# Apply cleaning to search text
df['clean_text'] = df['search_text'].apply(clean_text)

print("Text cleaned!")
print("\nBefore cleaning:")
print(df['search_text'][0])
print("\nAfter cleaning:")
print(df['clean_text'][0])

Text cleaned!

Before cleaning:
iPhone 13 Apple Electronics Smartphone Apple iPhone 13 is a premium smartphone designed for performance and comfort.

After cleaning:
iphone apple electronics smartphone apple iphone premium smartphone designed performance comfort

In [29]:
# Make sure price columns are numeric
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['discounted_price'] = pd.to_numeric(df['discounted_price'], errors='coerce')
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

# Fill any missing values
df['price'].fillna(df['price'].mean(), inplace=True)
df['discounted_price'].fillna(df['discounted_price'].mean(), inplace=True)
df['rating'].fillna(0, inplace=True)

print("Price columns cleaned!")
print("\nSample cleaned data:")
df[['product_name', 'price', 'discounted_price', 'rating', 'clean_text']].head()

Price columns cleaned!

Sample cleaned data:

,product_name,price,discounted_price,rating,clean_text
0,iPhone 13,65372,28109.96,3.7,iphone apple electronics smartphone apple ipho...
1,Zara Shirt,2616,1177.20,4.1,zara shirt zara fashion shirt zara zara shirt ...
2,RayBan Sunglasses,1305,548.10,3.6,rayban sunglasses rayban accessories sunglasse...
3,Puma Sneakers,7471,2988.40,3.5,puma sneakers puma footwear sneakers puma puma...
4,Nike T-shirt,1305,822.15,3.9,nike tshirt nike fashion tshirt nike nike tshi...

In [30]:
# Save cleaned dataframe
df.to_csv('cleaned_products.csv', index=False)

print("Cleaned data saved as 'cleaned_products.csv'")
print("Total products ready for search:", len(df))

Cleaned data saved as 'cleaned_products.csv'
Total products ready for search: 2000

# Build TF-IDF Search Engine 🔍

TF  = Term Frequency
      How many times a word appears in a product

IDF = Inverse Document Frequency
      How unique/rare that word is across all products

TF-IDF = Words that are important to THAT product
         but not common in ALL products

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
# Build TF-IDF vectorizer
vectorizer = TfidfVectorizer(
    max_features=5000,    # use top 5000 important words
    ngram_range=(1, 2),   # single words + two word phrases
    min_df=1              # include words that appear at least once
)

# Fit and transform the clean text
tfidf_matrix = vectorizer.fit_transform(df['clean_text'])

print("TF-IDF Matrix Built!")
print("Matrix Shape:", tfidf_matrix.shape)
print(f"  → {tfidf_matrix.shape[0]} products")
print(f"  → {tfidf_matrix.shape[1]} unique words/phrases")

TF-IDF Matrix Built!
Matrix Shape: (2000, 214)
  → 2000 products
  → 214 unique words/phrases

In [34]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def clean_query(query):
    # Clean the user query same way as products
    query = query.lower()
    query = re.sub(r'[^a-zA-Z\s]', '', query)
    words = query.split()
    words = [w for w in words if w not in stop_words]
    return ' '.join(words)

def search_products(query, top_n=5):
    
    # Step 1: Clean the query
    cleaned_query = clean_query(query)
    print(f"🔍 Searching for: '{query}'")
    print(f"   Cleaned query: '{cleaned_query}'\n")
    
    # Step 2: Convert query to TF-IDF vector
    query_vector = vectorizer.transform([cleaned_query])
    
    # Step 3: Calculate similarity with all products
    similarity_scores = cosine_similarity(query_vector, tfidf_matrix).flatten()
    
    # Step 4: Get top N most similar products
    top_indices = similarity_scores.argsort()[::-1][:top_n]
    
    # Step 5: Return results
    results = df.iloc[top_indices].copy()
    results['similarity_score'] = similarity_scores[top_indices]
    
    return results[['product_name', 'brand', 'category',
                     'subcategory', 'price', 'discounted_price',
                     'rating', 'stock_status', 'similarity_score']]

print("Search function ready!")

Search function ready!

### Test Basic Search

In [35]:
# Test 1 — Search by product type
print("=" * 50)
print("TEST 1: Search by product type")
print("=" * 50)
results = search_products("smartphone", top_n=5)
print(results.to_string())

==================================================
TEST 1: Search by product type
==================================================
🔍 Searching for: 'smartphone'
   Cleaned query: 'smartphone'

     product_name  brand     category subcategory  price  discounted_price  rating   stock_status  similarity_score
0       iPhone 13  Apple  Electronics  Smartphone  65372          28109.96     3.7  Limited Stock          0.358721
603     iPhone 13  Apple  Electronics  Smartphone  35063          26998.51     4.9  Limited Stock          0.358721
1060    iPhone 13  Apple  Electronics  Smartphone  73522          35290.56     3.8   Out of Stock          0.358721
1497    iPhone 13  Apple  Electronics  Smartphone  20876          13778.16     4.7       In Stock          0.358721
1501    iPhone 13  Apple  Electronics  Smartphone  50597          39971.63     3.9   Out of Stock          0.358721

### Test with Price Filter

In [36]:
def search_with_price(query, max_price=None, min_price=None, top_n=5):
    
    # Get TF-IDF results
    cleaned_query = clean_query(query)
    query_vector = vectorizer.transform([cleaned_query])
    similarity_scores = cosine_similarity(query_vector, tfidf_matrix).flatten()
    
    # Add scores to dataframe
    temp_df = df.copy()
    temp_df['similarity_score'] = similarity_scores
    
    # Apply price filter
    if max_price:
        temp_df = temp_df[temp_df['discounted_price'] <= max_price]
    if min_price:
        temp_df = temp_df[temp_df['discounted_price'] >= min_price]
    
    # Sort by similarity score
    temp_df = temp_df.sort_values('similarity_score', ascending=False).head(top_n)
    
    return temp_df[['product_name', 'brand', 'category',
                     'discounted_price', 'rating',
                     'stock_status', 'similarity_score']]

# Test price filter
print("=" * 50)
print("TEST 2: Budget phone under ₹20000")
print("=" * 50)
results = search_with_price("smartphone", max_price=20000, top_n=5)
print(results.to_string())

==================================================
TEST 2: Budget phone under ₹20000
==================================================
     product_name  brand     category  discounted_price  rating   stock_status  similarity_score
1497    iPhone 13  Apple  Electronics          13778.16     4.7       In Stock          0.358721
1747    iPhone 13  Apple  Electronics          10650.24     3.7  Limited Stock          0.358721
30      iPhone 13  Apple  Electronics          18649.54     4.9       In Stock          0.358721
1976    iPhone 13  Apple  Electronics          12834.80     3.9  Limited Stock          0.358721
971     iPhone 13  Apple  Electronics          14772.32     3.6   Out of Stock          0.358721

### Test Multiple Queries

In [37]:
# Test multiple real queries
test_queries = [
    ("nike shoes", None),
    ("sunglasses", None),
    ("laptop bag", None),
    ("fashion shirt", 2000),
]

for query, max_price in test_queries:
    print("=" * 50)
    if max_price:
        print(f"🔍 Query: '{query}' under ₹{max_price}")
        results = search_with_price(query, max_price=max_price, top_n=3)
    else:
        print(f"🔍 Query: '{query}'")
        results = search_products(query, top_n=3)
    print(results.to_string())
    print()

==================================================
🔍 Query: 'nike shoes'
🔍 Searching for: 'nike shoes'
   Cleaned query: 'nike shoes'

      product_name brand  category subcategory  price  discounted_price  rating   stock_status  similarity_score
1527  Nike Air Max  Nike  Footwear    Sneakers   4486           1480.38     3.7       In Stock           0.41581
1498  Nike Air Max  Nike  Footwear    Sneakers   8031           2891.16     4.1  Limited Stock           0.41581
1183  Nike Air Max  Nike  Footwear    Sneakers   9594           4125.42     4.5  Limited Stock           0.41581

==================================================
🔍 Query: 'sunglasses'
🔍 Searching for: 'sunglasses'
   Cleaned query: 'sunglasses'

           product_name   brand     category subcategory  price  discounted_price  rating   stock_status  similarity_score
249   RayBan Sunglasses  RayBan  Accessories  Sunglasses   4308           1852.44     3.5  Limited Stock          0.584461
1641  RayBan Sunglasses  RayBan  Accessories  Sunglasses   4992           3694.08     3.6       In Stock          0.584461
878   RayBan Sunglasses  RayBan  Accessories  Sunglasses   3632           2433.44     3.3       In Stock          0.584461

==================================================
🔍 Query: 'laptop bag'
🔍 Searching for: 'laptop bag'
   Cleaned query: 'laptop bag'

     product_name brand     category subcategory  price  discounted_price  rating   stock_status  similarity_score
722   Dell Laptop  Dell  Electronics      Laptop   8280           2566.80     4.9  Limited Stock          0.372852
1613  Dell Laptop  Dell  Electronics      Laptop  26259          22320.15     4.1   Out of Stock          0.372852
1328  Dell Laptop  Dell  Electronics      Laptop  27998          22958.36     4.7   Out of Stock          0.372852

==================================================
🔍 Query: 'fashion shirt' under ₹2000
     product_name brand category  discounted_price  rating  stock_status  similarity_score
1      Zara Shirt  Zara  Fashion           1177.20     4.1  Out of Stock          0.510997
284    Zara Shirt  Zara  Fashion            792.45     3.2  Out of Stock          0.510997
1145   Zara Shirt  Zara  Fashion           1102.08     4.4      In Stock          0.510997

In [40]:
import os
os.environ['NO_PROXY'] = '*'
os.environ['CURL_CA_BUNDLE'] = ''

from groq import Groq

GROQ_API_KEY = "###############################"  # paste your key here

client = Groq(api_key=GROQ_API_KEY)

# Test connection
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",  
    messages=[{"role": "user", "content": "Say hello!"}],
    max_tokens=50
)

print("Groq Connected!")
print("AI says:", response.choices[0].message.content)

Groq Connected!
AI says: Hello. How can I help you today?

In [41]:
def ai_rank_products(query, search_results):
    
    # Build product list for AI
    products_text = ""
    for i, (_, row) in enumerate(search_results.iterrows(), 1):
        products_text += f"""
        Product {i}:
        - Name        : {row['product_name']}
        - Brand       : {row['brand']}
        - Category    : {row['category']}
        - Price       : ₹{row['discounted_price']:,.0f}
        - Rating      : {row['rating']} ⭐
        - Stock       : {row['stock_status']}
        - Match Score : {row['similarity_score']:.2f}
        """
    
    prompt = f"""
    You are a smart Indian e-commerce product search assistant.
    
    Customer searched for: "{query}"
    
    Here are the top matching products found:
    {products_text}
    
    Your task:
    1. 🏆 Rank these products from best to worst match for the query
    2. 💰 Highlight the best value for money product
    3. ⭐ Highlight the highest rated product
    4. 💡 Give a one line buying tip for the customer
    5. 🎯 Recommend the single BEST product and explain why
    
    Keep response friendly, helpful and concise.
    Use Indian rupee ₹ for prices.
    """
    
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=600
    )
    
    return response.choices[0].message.content

print("AI Ranking function ready!")

AI Ranking function ready!

In [42]:
def smart_search(query, max_price=None, min_price=None,
                 category=None, top_n=5):
    
    print("=" * 55)
    print(f"  🔍 Smart Search: '{query}'")
    print("=" * 55)
    
    # Step 1: Get TF-IDF results
    cleaned_query = clean_query(query)
    query_vector  = vectorizer.transform([cleaned_query])
    scores        = cosine_similarity(query_vector, tfidf_matrix).flatten()
    
    temp_df                     = df.copy()
    temp_df['similarity_score'] = scores
    
    # Step 2: Apply filters
    if max_price:
        temp_df = temp_df[temp_df['discounted_price'] <= max_price]
        print(f"  💰 Max Price Filter : ₹{max_price:,}")
        
    if min_price:
        temp_df = temp_df[temp_df['discounted_price'] >= min_price]
        print(f"  💰 Min Price Filter : ₹{min_price:,}")
        
    if category:
        temp_df = temp_df[temp_df['category'].str.lower() == category.lower()]
        print(f"  📦 Category Filter  : {category}")
    
    # Step 3: Sort by similarity
    temp_df = temp_df.sort_values('similarity_score', ascending=False).head(top_n)
    
    if len(temp_df) == 0:
        print("\n❌ No products found! Try different filters.")
        return
    
    # Step 4: Show raw results
    print(f"\n📦 Top {len(temp_df)} Products Found:\n")
    display_cols = ['product_name', 'brand', 'category',
                    'discounted_price', 'rating',
                    'stock_status', 'similarity_score']
    print(temp_df[display_cols].to_string(index=False))
    
    # Step 5: Get AI ranking
    print("\n🤖 AI Analysis:\n")
    ai_response = ai_rank_products(query, temp_df)
    print(ai_response)
    print("=" * 55)

print("Smart Search function ready!")

Smart Search function ready!

In [43]:
# Test 1 — Simple search
smart_search("smartphone")

=======================================================
  🔍 Smart Search: 'smartphone'
=======================================================

📦 Top 5 Products Found:

product_name brand    category  discounted_price  rating  stock_status  similarity_score
   iPhone 13 Apple Electronics          28109.96     3.7 Limited Stock          0.358721
   iPhone 13 Apple Electronics          28777.63     3.3 Limited Stock          0.358721
   iPhone 13 Apple Electronics          48567.20     4.3      In Stock          0.358721
   iPhone 13 Apple Electronics          45940.08     3.5  Out of Stock          0.358721
   iPhone 13 Apple Electronics           7951.84     3.2  Out of Stock          0.358721

🤖 AI Analysis:

Namaste,

Ranking these products from best to worst match, I notice that they all have the same match score, so I'll prioritize based on other factors. Here are the highlights:

1. **Ranked Products**: Since all products are the same (iPhone 13), I'll rank them based on price: ₹7,952, ₹28,110, ₹28,778, ₹45,940, ₹48,567.
2. **Best Value for Money**: ₹28,110 (Product 1) seems to offer the best balance of price and rating.
3. **Highest Rated**: ₹48,567 (Product 3) has the highest rating of 4.3 ⭐.
4. **Buying Tip**: Always check the seller's ratings and reviews before making a purchase to ensure a smooth experience.
5. **Recommended Product**: I recommend **Product 1: iPhone 13 for ₹28,110** because it offers a good balance of price, rating (3.7 ⭐), and limited stock availability, making it a relatively affordable and reliable option.

Happy shopping!
=======================================================

In [44]:
# Test 2 — Budget search
smart_search("budget phone", max_price=20000)

=======================================================
  🔍 Smart Search: 'budget phone'
=======================================================
  💰 Max Price Filter : ₹20,000

📦 Top 5 Products Found:

     product_name  brand category  discounted_price  rating  stock_status  similarity_score
       Zara Shirt   Zara  Fashion           1177.20     4.1  Out of Stock               0.0
     Nike Air Max   Nike Footwear           2980.10     5.0 Limited Stock               0.0
Adidas Ultraboost Adidas Footwear           2099.26     3.4  Out of Stock               0.0
    Puma Sneakers   Puma Footwear           5327.13     4.1      In Stock               0.0
     Reebok Shoes Reebok Footwear           2693.90     3.3  Out of Stock               0.0

🤖 AI Analysis:

It looks like none of the products match your search for a "budget phone".

1. **Ranking**: Unfortunately, all products have a 0.00 match score, so there's no ranking to provide.
2. **Best Value**: Since none of the products match your search, I couldn't determine the best value for money.
3. **Highest Rated**: The Nike Air Max is the highest rated product with 5.0 ⭐, but it's a footwear product, not a phone.
4. **Buying Tip**: Consider checking the electronics or mobile section for budget phone options.
5. **Recommended Product**: None of the listed products are a good match for your search. I recommend exploring our mobile category for budget-friendly phone options.

Let me help you find a budget phone that suits your needs. Would you like me to show you some options?
=======================================================

In [45]:
# Test 3 — Category + price
smart_search("running shoes", max_price=5000, category="Footwear")

=======================================================
  🔍 Smart Search: 'running shoes'
=======================================================
  💰 Max Price Filter : ₹5,000
  📦 Category Filter  : Footwear

📦 Top 5 Products Found:

     product_name  brand category  discounted_price  rating stock_status  similarity_score
Adidas Ultraboost Adidas Footwear           2458.28     3.4 Out of Stock          0.521221
Adidas Ultraboost Adidas Footwear           1227.24     4.5 Out of Stock          0.521221
Adidas Ultraboost Adidas Footwear           4801.68     4.9     In Stock          0.521221
Adidas Ultraboost Adidas Footwear           3581.10     3.9 Out of Stock          0.521221
Adidas Ultraboost Adidas Footwear           1965.48     3.5     In Stock          0.521221

🤖 AI Analysis:

Namaste, I've got the results for you.

**Ranking:**
1. Product 3: ₹4,802 (In Stock, 4.9⭐)
2. Product 5: ₹1,965 (In Stock, 3.5⭐)
3. Product 4: ₹3,581 (Out of Stock, 3.9⭐)
4. Product 2: ₹1,227 (Out of Stock, 4.5⭐)
5. Product 1: ₹2,458 (Out of Stock, 3.4⭐)

**Best Value for Money:** 💰 Product 5: ₹1,965 (In Stock, 3.5⭐) - A good balance of price and rating.

**Highest Rated:** ⭐ Product 3: ₹4,802 (In Stock, 4.9⭐) - Excellent rating, but pricey.

**Buying Tip:** 💡 Consider both price and availability when making your decision.

**Recommended Product:** 🎯 I recommend **Product 5: ₹1,965** because it's in stock, has a decent rating, and offers a good balance of price and quality.
=======================================================

In [46]:
# Test 4 — Premium product
smart_search("premium watch", min_price=2000)

=======================================================
  🔍 Smart Search: 'premium watch'
=======================================================
  💰 Min Price Filter : ₹2,000

📦 Top 5 Products Found:

product_name  brand    category  discounted_price  rating stock_status  similarity_score
Fossil Watch Fossil Accessories           2646.16     4.7 Out of Stock          0.515027
Fossil Watch Fossil Accessories           3667.04     3.5 Out of Stock          0.515027
Fossil Watch Fossil Accessories           2183.07     3.9 Out of Stock          0.515027
Fossil Watch Fossil Accessories           3771.50     4.0     In Stock          0.515027
Fossil Watch Fossil Accessories           3697.65     4.9 Out of Stock          0.515027

🤖 AI Analysis:

Namaste,

Based on your search for "premium watch", I've got the top matches for you:

1. **Ranking**: Since all products have the same match score (0.52), I'll rank them by their rating:
   - Product 5: Fossil Watch (₹3,698, 4.9⭐)
   - Product 1: Fossil Watch (₹2,646, 4.7⭐)
   - Product 4: Fossil Watch (₹3,772, 4.0⭐)
   - Product 3: Fossil Watch (₹2,183, 3.9⭐)
   - Product 2: Fossil Watch (₹3,667, 3.5⭐)

2. **Best Value for Money**: Product 1: Fossil Watch (₹2,646, 4.7⭐) seems to be the best value for money, considering its high rating and relatively lower price.

3. **Highest Rated**: Product 5: Fossil Watch (₹3,698, 4.9⭐) is the highest rated product among the options.

4. **Buying Tip**: When purchasing a premium watch, consider checking the warranty and after-sales service offered by the brand for a hassle-free experience.

5. **Recommended Product**: I'd recommend Product 4: Fossil Watch (₹3,772, 4.0⭐) as it's the only one **In Stock**, ensuring you can get your hands on it immediately. Although it's not the highest rated, its availability and decent rating make it a practical choice.
=======================================================

In [47]:
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

In [48]:
# ============================================
#   🛍️ AI SMART PRODUCT SEARCH ENGINE
# ============================================

# --- Styles ---
display(HTML("""
<style>
    .search-title {
        background: linear-gradient(135deg, #f093fb, #f5576c);
        color: white;
        padding: 25px;
        border-radius: 15px;
        text-align: center;
        font-size: 26px;
        font-weight: bold;
        margin-bottom: 20px;
        letter-spacing: 1px;
    }
    .product-card {
        background: white;
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        padding: 15px;
        margin: 8px 0;
        box-shadow: 2px 2px 8px rgba(0,0,0,0.08);
    }
    .product-name {
        font-size: 17px;
        font-weight: bold;
        color: #2d3436;
    }
    .product-price {
        font-size: 20px;
        font-weight: bold;
        color: #e84393;
    }
    .product-rating {
        color: #f39c12;
        font-size: 15px;
    }
    .stock-in {
        background: #d4edda;
        color: #155724;
        padding: 3px 10px;
        border-radius: 20px;
        font-size: 12px;
    }
    .stock-out {
        background: #f8d7da;
        color: #721c24;
        padding: 3px 10px;
        border-radius: 20px;
        font-size: 12px;
    }
    .stock-limited {
        background: #fff3cd;
        color: #856404;
        padding: 3px 10px;
        border-radius: 20px;
        font-size: 12px;
    }
    .ai-box {
        background: linear-gradient(135deg, #667eea22, #764ba222);
        border-left: 5px solid #667eea;
        padding: 20px;
        border-radius: 10px;
        margin-top: 15px;
        font-size: 15px;
        line-height: 1.8;
    }
    .filter-section {
        background: #f8f9fa;
        padding: 15px;
        border-radius: 10px;
        margin-bottom: 15px;
    }
    .result-header {
        background: linear-gradient(90deg, #667eea, #764ba2);
        color: white;
        padding: 10px 20px;
        border-radius: 8px;
        font-size: 16px;
        font-weight: bold;
        margin: 15px 0 10px 0;
    }
    .no-result {
        background: #fff3cd;
        border-left: 5px solid #ffc107;
        padding: 15px;
        border-radius: 8px;
        font-size: 15px;
    }
</style>
"""))

# --- Title ---
display(HTML('<div class="search-title">🛍️ AI Smart Product Search Engine</div>'))

# --- Search Input ---
search_input = widgets.Text(
    placeholder='🔍 Search anything... e.g. budget phone, nike shoes, premium watch',
    layout=widgets.Layout(width='620px', height='45px'),
)

# --- Filters ---
max_price_input = widgets.BoundedIntText(
    value=0,
    min=0,
    max=500000,
    description='💰 Max Price ₹:',
    layout=widgets.Layout(width='250px'),
    style={'description_width': '120px'}
)

min_price_input = widgets.BoundedIntText(
    value=0,
    min=0,
    max=500000,
    description='💎 Min Price ₹:',
    layout=widgets.Layout(width='250px'),
    style={'description_width': '120px'}
)

category_input = widgets.Dropdown(
    options=['All', 'Electronics', 'Fashion', 'Footwear', 'Accessories'],
    value='All',
    description='📦 Category:',
    layout=widgets.Layout(width='250px'),
    style={'description_width': '120px'}
)

top_n_input = widgets.Dropdown(
    options=[3, 5, 7, 10],
    value=5,
    description='📊 Results:',
    layout=widgets.Layout(width='200px'),
    style={'description_width': '100px'}
)

# --- Search Button ---
search_btn = widgets.Button(
    description='🔍 Search Now',
    button_style='danger',
    layout=widgets.Layout(width='200px', height='45px')
)

# --- Clear Button ---
clear_btn = widgets.Button(
    description='🗑️ Clear',
    button_style='warning',
    layout=widgets.Layout(width='100px', height='45px')
)

# --- Output ---
output = widgets.Output()

# --- Stock Badge Helper ---
def stock_badge(status):
    if status == 'In Stock':
        return f'<span class="stock-in">✅ {status}</span>'
    elif status == 'Out of Stock':
        return f'<span class="stock-out">❌ {status}</span>'
    else:
        return f'<span class="stock-limited">⚠️ {status}</span>'

# --- Search Button Click ---
def on_search(btn):
    with output:
        clear_output()

        query = search_input.value.strip()

        if not query:
            display(HTML('<div class="no-result">⚠️ Please enter something to search!</div>'))
            return

        # Get filter values
        max_price = max_price_input.value if max_price_input.value > 0 else None
        min_price = min_price_input.value if min_price_input.value > 0 else None
        category  = None if category_input.value == 'All' else category_input.value
        top_n     = top_n_input.value

        # Show loading
        display(HTML(f'''
        <div style="text-align:center; padding:30px; font-size:18px;">
            ⏳ Searching for <b>"{query}"</b>... Please wait...
        </div>'''))

        try:
            # TF-IDF Search
            cleaned_query = clean_query(query)
            query_vector  = vectorizer.transform([cleaned_query])
            scores        = cosine_similarity(query_vector, tfidf_matrix).flatten()

            temp_df                     = df.copy()
            temp_df['similarity_score'] = scores

            # Apply filters
            if max_price:
                temp_df = temp_df[temp_df['discounted_price'] <= max_price]
            if min_price:
                temp_df = temp_df[temp_df['discounted_price'] >= min_price]
            if category:
                temp_df = temp_df[temp_df['category'].str.lower() == category.lower()]

            # Sort and get top N
            temp_df = temp_df.sort_values('similarity_score', ascending=False).head(top_n)

            clear_output()

            if len(temp_df) == 0:
                display(HTML('<div class="no-result">❌ No products found! Try changing filters.</div>'))
                return

            # Show result header
            display(HTML(f'<div class="result-header">📦 {len(temp_df)} Products Found for "{query}"</div>'))

            # Show product cards
            for _, row in temp_df.iterrows():
                match_pct = int(row['similarity_score'] * 100)
                display(HTML(f"""
                <div class="product-card">
                    <div class="product-name">
                        {row['product_name']} — {row['brand']}
                    </div>
                    <div style="margin:6px 0;">
                        <span class="product-price">₹{row['discounted_price']:,.0f}</span>
                        &nbsp;&nbsp;
                        <span style="color:#999; text-decoration:line-through;">
                            ₹{row['price']:,.0f}
                        </span>
                        &nbsp;&nbsp;
                        <span style="color:green; font-weight:bold;">
                            {row['discount_percent']}% off
                        </span>
                    </div>
                    <div class="product-rating">
                        {'⭐' * int(row['rating'])} {row['rating']}
                        &nbsp;|&nbsp; {stock_badge(row['stock_status'])}
                        &nbsp;|&nbsp; 📂 {row['category']} → {row['subcategory']}
                        &nbsp;|&nbsp; 🎯 Match: {match_pct}%
                    </div>
                </div>
                """))

            # Get AI Analysis
            display(HTML('<div class="result-header">🤖 AI Analysis & Recommendation</div>'))
            display(HTML('<div style="padding:10px; font-size:14px;">⏳ Getting AI recommendation...</div>'))

            ai_response = ai_rank_products(query, temp_df)

            clear_output(wait=True)

            # Re-show product cards after clear
            display(HTML(f'<div class="result-header">📦 {len(temp_df)} Products Found for "{query}"</div>'))

            for _, row in temp_df.iterrows():
                match_pct = int(row['similarity_score'] * 100)
                display(HTML(f"""
                <div class="product-card">
                    <div class="product-name">
                        {row['product_name']} — {row['brand']}
                    </div>
                    <div style="margin:6px 0;">
                        <span class="product-price">₹{row['discounted_price']:,.0f}</span>
                        &nbsp;&nbsp;
                        <span style="color:#999; text-decoration:line-through;">
                            ₹{row['price']:,.0f}
                        </span>
                        &nbsp;&nbsp;
                        <span style="color:green; font-weight:bold;">
                            {row['discount_percent']}% off
                        </span>
                    </div>
                    <div class="product-rating">
                        {'⭐' * int(row['rating'])} {row['rating']}
                        &nbsp;|&nbsp; {stock_badge(row['stock_status'])}
                        &nbsp;|&nbsp; 📂 {row['category']} → {row['subcategory']}
                        &nbsp;|&nbsp; 🎯 Match: {match_pct}%
                    </div>
                </div>
                """))

            # Show AI response
            display(HTML(f'''
            <div class="result-header">🤖 AI Analysis & Recommendation</div>
            <div class="ai-box">{ai_response.replace(chr(10), "<br>")}</div>
            '''))

        except Exception as e:
            display(HTML(f'<div class="no-result">❌ Error: {str(e)}</div>'))

# --- Clear Button Click ---
def on_clear(btn):
    with output:
        clear_output()
    search_input.value    = ''
    max_price_input.value = 0
    min_price_input.value = 0
    category_input.value  = 'All'

# --- Connect Buttons ---
search_btn.on_click(on_search)
clear_btn.on_click(on_clear)

# --- Layout ---
display(HTML('<div class="filter-section">'))
display(search_input)
display(widgets.HBox([max_price_input, min_price_input]))
display(widgets.HBox([category_input, top_n_input]))
display(widgets.HBox([search_btn, clear_btn]))
display(HTML('</div>'))
display(output)

Text(value='', layout=Layout(height='45px', width='620px'), placeholder='🔍 Search anything... e.g. budget phon…

HBox(children=(BoundedIntText(value=0, description='💰 Max Price ₹:', layout=Layout(width='250px'), max=500000,…

HBox(children=(Dropdown(description='📦 Category:', layout=Layout(width='250px'), options=('All', 'Electronics'…

HBox(children=(Button(button_style='danger', description='🔍 Search Now', layout=Layout(height='45px', width='2…

Output()